# Generated by Django 5.0.1 on 2025-10-28 12:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('factor_type', models.CharField(choices=[('seasonal', 'Seasonal Demand'), ('fabric_complexity', 'Fabric Complexity'), ('customer_loyalty', 'Customer Loyalty'), ('urgency', 'Urgency Level'), ('competition', 'Competition Factor'), ('economic', 'Economic Factor'), ('skill_level', 'Required Skill Level'), ('volume', 'Order Volume')], max_length=30)),
                ('weight', models.FloatField(help_text='Weight of this factor in pricing calculation (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('multiplier_range_min', models.FloatField(help_text='Minimum multiplier value', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('multiplier_range_max', models.FloatField(help_text='Maximum multiplier value', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['factor_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('if_then', 'If-Then Rule'), ('threshold', 'Threshold Rule'), ('percentage', 'Percentage Rule'), ('fixed', 'Fixed Amount Rule')], max_length=20)),
                ('condition', models.JSONField(help_text='Condition logic in JSON format')),
                ('action', models.JSONField(help_text='Action to take when condition is met')),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPricingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_tier', models.CharField(choices=[('new', 'New Customer'), ('regular', 'Regular Customer'), ('vip', 'VIP Customer'), ('wholesale', 'Wholesale Customer')], default='new', max_length=20)),
                ('discount_percentage', models.FloatField(default=0.0, help_text='Maximum discount percentage for this customer', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50.0)])),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_orders', models.IntegerField(default=0)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reliability_score', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.customer')),
                ('preferred_services', models.ManyToManyField(blank=True, to='services.service')),
            ],
            options={
                'ordering': ['-loyalty_tier', '-average_order_value'],
            },
        ),
        migrations.CreateModel(
            name='PricingAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_reason', models.TextField()),
                ('changed_by', models.CharField(max_length=200)),
                ('change_type', models.CharField(choices=[('manual', 'Manual Adjustment'), ('ai', 'AI Recommendation'), ('rule', 'Rule-based Change'), ('seasonal', 'Seasonal Adjustment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.pricingarea')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factors', models.JSONField(help_text='Factors that influenced this pricing')),
                ('customer_segment', models.CharField(blank=True, max_length=50)),
                ('order_volume', models.IntegerField(default=1)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('fabric_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('complexity_score', models.FloatField(blank=True, null=True)),
                ('success_rate', models.FloatField(blank=True, help_text='Customer satisfaction/order success rate', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.pricingarea')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prediction_accuracy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('model_version', models.CharField(max_length=20)),
                ('input_features', models.JSONField(help_text='Features used for prediction')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.pricingarea')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='DynamicPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_score', models.FloatField(help_text='ML model confidence in this pricing', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('factors_applied', models.JSONField(help_text='Factors and their impact')),
                ('pricing_version', models.CharField(default='v1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.pricingarea')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('service', 'area', 'pricing_version')},
            },
        ),
    ]
